Repository carpentries-incubator/R-help-reprexes, pull requests merged in 2024-12, with the labels that each got.

#92 Update README.md
  README.md
Labels: type:documentation

#93 Peter acting on edits from Kaija and Xochitl
  .DS_Store
  .gitignore
  episodes/.DS_Store
  episodes/2-identify-the-problem.Rmd
Labels: episode:understanding code

#89 Update setup.md
  learners/setup.md
Labels: help wanted, type:lesson design, type: template and tools
